ci cd yml added

diff --git a/.github/workflows/deploy.yaml b/.github/workflows/deploy.yaml
--- a/.github/workflows/deploy.yaml
+++ b/.github/workflows/deploy.yaml
@@ -22,15 +22,25 @@ jobs:
           php-version: "8.2"
           extensions: pdo_mysql
 
-      # Step 3: Install dependencies
+      # Step 3: Install Composer dependencies
       - name: Install Composer Dependencies
         run: composer install --no-scripts --no-interaction --prefer-dist --dev
 
-      # Step 4: Run static code analysis
+      # Step 4: Verify PHPStan installation and run static code analysis
+      - name: Check PHPStan Installation
+        run: |
+          if [ -f vendor/bin/phpstan ]; then
+            echo "PHPStan found!";
+          else
+            echo "PHPStan not found. Please check your composer.json file.";
+            exit 1;
+          fi
+
+      # Step 5: Run PHPStan analysis
       - name: Run PHPStan
         run: vendor/bin/phpstan analyse
 
-      # Step 5: Run PHPUnit tests
+      # Step 6: Run PHPUnit tests
       - name: Run PHPUnit Tests
         run: vendor/bin/phpunit --testdox
 
